/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AuthSession {
    'id': string;
    'kind': AuthSessionKindEnum;
    'current': boolean;
    'provider': string;
    'login': string;
    'label': string;
    'userAgent'?: string;
    'createdAt': string;
    'lastSeenAt': string;
    'expiresAt': string;
    'revocable': boolean;
}

export const AuthSessionKindEnum = {
    BROWSER: 'browser',
    CLI: 'cli'
} as const;

export type AuthSessionKindEnum = typeof AuthSessionKindEnum[keyof typeof AuthSessionKindEnum];


