/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BilledTokenCounts } from './billed-token-counts';
// May contain unused imports in some cases
// @ts-ignore
import type { BillingModelRef } from './billing-model-ref';

/**
 * Billing statistics grouped by model.
 */
export interface BillingByModel {
    'model': BillingModelRef;
    /**
     * Number of usage-bearing stage visits that used this model.
     */
    'stages': number;
    'billing': BilledTokenCounts;
}

