/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Board column status for a run in the list view.
 */

export const BoardColumn = {
    INITIALIZING: 'initializing',
    RUNNING: 'running',
    BLOCKED: 'blocked',
    SUCCEEDED: 'succeeded',
    FAILED: 'failed'
} as const;

export type BoardColumn = typeof BoardColumn[keyof typeof BoardColumn];



