/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Status bucket for a run, shared by list and kanban renderings and by the `status` query parameter on `GET /api/v1/runs`. The `archived` bucket is orthogonal to the `include_archived` flag — passing `status=archived` is equivalent to opting archived runs in.
 */

export const BoardColumn = {
    QUEUED: 'queued',
    INITIALIZING: 'initializing',
    RUNNING: 'running',
    BLOCKED: 'blocked',
    SUCCEEDED: 'succeeded',
    FAILED: 'failed',
    ARCHIVED: 'archived',
    REMOVING: 'removing'
} as const;

export type BoardColumn = typeof BoardColumn[keyof typeof BoardColumn];
