/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunCheckpoint } from './run-checkpoint';
// May contain unused imports in some cases
// @ts-ignore
import type { RunDiff } from './run-diff';

/**
 * Sequence-tagged checkpoint history entry with the diff observed at that checkpoint.
 */
export interface CheckpointRecord {
    'seq': number;
    'checkpoint': RunCheckpoint;
    'diff': RunDiff;
}

