/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BilledTokenCounts } from './billed-token-counts';
// May contain unused imports in some cases
// @ts-ignore
import type { RunDiff } from './run-diff';
// May contain unused imports in some cases
// @ts-ignore
import type { RunFailure } from './run-failure';
// May contain unused imports in some cases
// @ts-ignore
import type { StageOutcome } from './stage-outcome';
// May contain unused imports in some cases
// @ts-ignore
import type { StageSummary } from './stage-summary';

/**
 * Terminal run conclusion derived from final workflow execution.
 */
export interface Conclusion {
    'timestamp': string;
    'status': StageOutcome;
    'duration_ms': number;
    'failure'?: RunFailure | null;
    'final_git_commit_sha'?: string | null;
    'stages': Array<StageSummary>;
    'billing'?: BilledTokenCounts | null;
    'total_retries': number;
    'diff': RunDiff;
}



