/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationTarget } from './automation-target';
// May contain unused imports in some cases
// @ts-ignore
import type { AutomationTrigger } from './automation-trigger';

/**
 * Request body for creating an automation.
 */
export interface CreateAutomationRequest {
    'id': string;
    'name': string;
    'description'?: string | null;
    'target': AutomationTarget;
    'triggers': Array<AutomationTrigger>;
}
