/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentApiImageSettings } from './environment-api-image-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentLifecycleSettings } from './environment-lifecycle-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentNetworkSettings } from './environment-network-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentProvider } from './environment-provider';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentResourcesSettings } from './environment-resources-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentVolumeSettings } from './environment-volume-settings';

/**
 * Request body for creating a server-managed environment.
 */
export interface CreateEnvironmentRequest {
    'id': string;
    'provider': EnvironmentProvider;
    'image': EnvironmentApiImageSettings;
    'resources': EnvironmentResourcesSettings;
    'network': EnvironmentNetworkSettings;
    'lifecycle': EnvironmentLifecycleSettings;
    'labels': { [key: string]: string; };
    'volumes': Array<EnvironmentVolumeSettings>;
    'env': { [key: string]: string; };
}
