/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DaytonaNetworkLayer } from './daytona-network-layer';
// May contain unused imports in some cases
// @ts-ignore
import type { DaytonaSnapshotSettings } from './daytona-snapshot-settings';

export interface DaytonaSettings {
    'auto_stop_interval': number | null;
    'labels': { [key: string]: string; };
    'snapshot': DaytonaSnapshotSettings | null;
    'network': DaytonaNetworkLayer | null;
}

