/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Cheap aggregate file and line counts for a run diff.
 */
export interface DiffSummary {
    /**
     * Total number of changed files, including binary files.
     */
    'files_changed': number;
    /**
     * Total lines added across text files.
     */
    'additions': number;
    /**
     * Total lines deleted across text files.
     */
    'deletions': number;
}
