/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Environment } from './environment';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentListMeta } from './environment-list-meta';

/**
 * List envelope for environment definitions.
 */
export interface EnvironmentListResponse {
    'data': Array<Environment>;
    'meta': EnvironmentListMeta;
}
