/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExecOutputTail } from './exec-output-tail';
// May contain unused imports in some cases
// @ts-ignore
import type { FailureCategory } from './failure-category';
// May contain unused imports in some cases
// @ts-ignore
import type { SystemActorKind } from './system-actor-kind';

/**
 * Rich diagnostic detail for a failed stage or terminal run.
 */
export interface FailureDetail {
    'message': string;
    'causes'?: Array<string>;
    'category': FailureCategory;
    'system_actor'?: SystemActorKind | null;
    /**
     * Stable normalized signature for grouping related failures.
     */
    'signature'?: string | null;
    'exec_output_tail'?: ExecOutputTail | null;
}



