/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IntegrationConnectionKind } from './integration-connection-kind';
// May contain unused imports in some cases
// @ts-ignore
import type { IntegrationConnectionState } from './integration-connection-state';

/**
 * Live connection status for integrations with persistent connections.
 */
export interface IntegrationConnectionStatus {
    'kind': IntegrationConnectionKind;
    'status': IntegrationConnectionState;
    /**
     * Last time this integration established its live connection.
     */
    'last_connected_at': string | null;
    /**
     * Sanitized last connection error, if any.
     */
    'last_error': string | null;
}
