/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Computed runtime integration status.
 */

export const IntegrationStatus = {
    DISABLED: 'disabled',
    MISSING_CREDENTIALS: 'missing_credentials',
    CONFIGURED: 'configured',
    CONNECTING: 'connecting',
    CONNECTED: 'connected',
    ERROR: 'error'
} as const;

export type IntegrationStatus = typeof IntegrationStatus[keyof typeof IntegrationStatus];
