/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Sparse command-local args that affect run settings.
 */
export interface ManifestArgs {
    'model'?: string;
    'provider'?: string;
    'sandbox'?: string;
    /**
     * Per-run Docker sandbox image override.
     */
    'docker_image'?: string;
    'verbose'?: boolean;
    'dry_run'?: boolean;
    'auto_approve'?: boolean;
    'no_retro'?: boolean;
    'preserve_sandbox'?: boolean;
    /**
     * Override `run.sandbox.local.worktree_mode` (e.g. `never` for `--in-place`). 
     */
    'worktree_mode'?: string;
    'label'?: Array<string>;
    /**
     * Raw repeated CLI input overrides, each in `KEY=VALUE` form.
     */
    'input'?: Array<string>;
}

