/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FileDiff } from './file-diff';
// May contain unused imports in some cases
// @ts-ignore
import type { RunFilesMeta } from './run-files-meta';

/**
 * List of file diffs produced by a run, with metadata describing truncation and degraded-response state.  Naturally bounded: at most 200 files per response. Consumers should inspect `meta.truncated` rather than assuming `data.length` equals the run\'s total change count. 
 */
export interface PaginatedRunFileList {
    'data': Array<FileDiff>;
    'meta': RunFilesMeta;
}

