/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunCommit } from './run-commit';
// May contain unused imports in some cases
// @ts-ignore
import type { RunCommitsMeta } from './run-commits-meta';

/**
 * Git commits on a run branch since the run base.
 */
export interface PaginatedRunCommitList {
    'data': Array<RunCommit>;
    'meta': RunCommitsMeta;
}

