/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BoardColumnDefinition } from './board-column-definition';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMeta } from './pagination-meta';
// May contain unused imports in some cases
// @ts-ignore
import type { Run } from './run';

/**
 * Paginated list of board runs with shared canonical fields plus board metadata.
 */
export interface PaginatedBoardRunList {
    'columns': Array<BoardColumnDefinition>;
    'data': Array<Run>;
    'meta': PaginationMeta;
}

