/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InterviewQuestionRecord } from './interview-question-record';

/**
 * Pending interview question plus the time it entered the unresolved set.
 */
export interface PendingInterviewRecord {
    'question': InterviewQuestionRecord;
    'started_at': string;
}

