/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestDetails } from './pull-request-details';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestLink } from './pull-request-link';

/**
 * Stored pull request link plus optional live GitHub details.
 */
export interface PullRequest {
    'link': PullRequestLink;
    'details'?: PullRequestDetails | null;
}

