/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Persisted record of a pull request created for a run.
 */
export interface PullRequest {
    'provider': PullRequestProviderEnum;
    'html_url': string;
    'number': number;
    'owner': string;
    'repo': string;
    'base_branch': string;
    'head_branch': string;
    'title': string;
}

export const PullRequestProviderEnum = {
    GITHUB: 'github'
} as const;

export type PullRequestProviderEnum = typeof PullRequestProviderEnum[keyof typeof PullRequestProviderEnum];


