/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Why live GitHub pull request details are unavailable.
 */

export const PullRequestDetailsUnavailableReason = {
    INTEGRATION_UNAVAILABLE: 'integration_unavailable',
    NOT_FOUND: 'not_found',
    FETCH_FAILED: 'fetch_failed'
} as const;

export type PullRequestDetailsUnavailableReason = typeof PullRequestDetailsUnavailableReason[keyof typeof PullRequestDetailsUnavailableReason];



