/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestDetailsStatus } from './pull-request-details-status';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestDetailsUnavailableReason } from './pull-request-details-unavailable-reason';

/**
 * Metadata for live GitHub detail retrieval.
 */
export interface PullRequestMeta {
    'details_status': PullRequestDetailsStatus;
    'details_unavailable_reason'?: PullRequestDetailsUnavailableReason | null;
}



