/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DiffSummary } from './diff-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { PendingInterviewRecord } from './pending-interview-record';
// May contain unused imports in some cases
// @ts-ignore
import type { RunCheckpoint } from './run-checkpoint';
// May contain unused imports in some cases
// @ts-ignore
import type { RunControlAction } from './run-control-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RunProjectionCheckpointsInnerInner } from './run-projection-checkpoints-inner-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { RunSpec } from './run-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatus } from './run-status';
// May contain unused imports in some cases
// @ts-ignore
import type { StageProjection } from './stage-projection';

/**
 * Raw internal run projection derived from the event log.
 */
export interface RunProjection {
    'spec'?: RunSpec | null;
    'graph_source'?: string | null;
    'start'?: { [key: string]: any; } | null;
    'status'?: RunStatus | null;
    'status_updated_at'?: string | null;
    'last_event_at'?: string | null;
    'pending_control'?: RunControlAction | null;
    'checkpoint'?: RunCheckpoint | null;
    /**
     * Sequence-tagged checkpoint history entries as `[seq, checkpoint]`.
     */
    'checkpoints'?: Array<Array<RunProjectionCheckpointsInnerInner>>;
    'conclusion'?: { [key: string]: any; } | null;
    'retro'?: { [key: string]: any; } | null;
    'retro_prompt'?: string | null;
    'retro_response'?: string | null;
    'sandbox'?: { [key: string]: any; } | null;
    'final_patch'?: string | null;
    'diff_summary'?: DiffSummary | null;
    'pull_request'?: { [key: string]: any; } | null;
    'superseded_by'?: string | null;
    'pending_interviews'?: { [key: string]: PendingInterviewRecord; };
    /**
     * Map from StageId (`node_id@visit`) to stage projection data.
     */
    'stages': { [key: string]: StageProjection; };
}



