/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DiffSummary } from './diff-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { RepositoryReference } from './repository-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { RunControlAction } from './run-control-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatus } from './run-status';

/**
 * Durable run summary derived from the backing store.
 */
export interface RunSummary {
    'run_id': string;
    'workflow_name'?: string | null;
    'workflow_slug'?: string | null;
    'goal': string;
    'title': string;
    'labels': { [key: string]: string; };
    'source_directory'?: string | null;
    'in_place'?: boolean;
    'repo_origin_url'?: string | null;
    'repository': RepositoryReference;
    'start_time'?: string | null;
    'created_at': string;
    'last_event_at'?: string | null;
    'status': RunStatus;
    'pending_control'?: RunControlAction | null;
    'duration_ms'?: number | null;
    'elapsed_secs'?: number | null;
    'total_usd_micros'?: number | null;
    'superseded_by'?: string | null;
    'diff_summary'?: DiffSummary | null;
}



