/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BlockedReason } from './blocked-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { FailureReason } from './failure-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusBlocked } from './run-status-blocked';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusDead } from './run-status-dead';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusFailed } from './run-status-failed';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusPaused } from './run-status-paused';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusQueued } from './run-status-queued';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusRemoving } from './run-status-removing';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusRunning } from './run-status-running';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusStarting } from './run-status-starting';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusSubmitted } from './run-status-submitted';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusSucceeded } from './run-status-succeeded';

/**
 * @type RunStatus
 * Execution status of a run. Archive state is represented separately on `RunLifecycle.archived` so terminal status payloads remain intact. 
 */
export type RunStatus = { kind: 'blocked' } & RunStatusBlocked | { kind: 'dead' } & RunStatusDead | { kind: 'failed' } & RunStatusFailed | { kind: 'paused' } & RunStatusPaused | { kind: 'queued' } & RunStatusQueued | { kind: 'removing' } & RunStatusRemoving | { kind: 'running' } & RunStatusRunning | { kind: 'starting' } & RunStatusStarting | { kind: 'submitted' } & RunStatusSubmitted | { kind: 'succeeded' } & RunStatusSucceeded;


