/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunCommitParent } from './run-commit-parent';
// May contain unused imports in some cases
// @ts-ignore
import type { RunCommitPerson } from './run-commit-person';

/**
 * A Git commit on a run branch.
 */
export interface RunCommit {
    'sha': string;
    'short_sha': string;
    'parents': Array<RunCommitParent>;
    'author': RunCommitPerson;
    'committer': RunCommitPerson;
    'subject': string;
    'body'?: string | null;
    'message': string;
    'trailers': { [key: string]: string; };
    'tree_sha': string | null;
}

