/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunSandboxRuntime } from './run-sandbox-runtime';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxProvider } from './sandbox-provider';

/**
 * Canonical sandbox environment record for a run.
 */
export interface RunSandbox {
    'provider': SandboxProvider;
    'image': string | null;
    'snapshot': string | null;
    'runtime': RunSandboxRuntime | null;
}



