/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DiffSummary } from './diff-summary';

/**
 * Patch text and aggregate counts captured for a run-level diff.
 */
export interface RunDiff {
    'patch'?: string | null;
    'summary'?: DiffSummary | null;
}

