/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Metadata for a `PaginatedRunCommitList` response.
 */
export interface RunCommitsMeta {
    'source': RunCommitsMetaSourceEnum;
    'base_sha': string;
    'head_sha': string;
    'limit': number;
    'total_returned': number;
    'truncated': boolean;
}

export const RunCommitsMetaSourceEnum = {
    SANDBOX: 'sandbox'
} as const;

export type RunCommitsMetaSourceEnum = typeof RunCommitsMetaSourceEnum[keyof typeof RunCommitsMetaSourceEnum];


