/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckpointRecord } from './checkpoint-record';
// May contain unused imports in some cases
// @ts-ignore
import type { Conclusion } from './conclusion';
// May contain unused imports in some cases
// @ts-ignore
import type { PendingInterviewRecord } from './pending-interview-record';
// May contain unused imports in some cases
// @ts-ignore
import type { RunControlAction } from './run-control-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RunSandbox } from './run-sandbox';
// May contain unused imports in some cases
// @ts-ignore
import type { RunSpec } from './run-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatus } from './run-status';
// May contain unused imports in some cases
// @ts-ignore
import type { StageProjection } from './stage-projection';
// May contain unused imports in some cases
// @ts-ignore
import type { StartRecord } from './start-record';

/**
 * Raw internal run projection derived from the event log.
 */
export interface RunProjection {
    /**
     * Resolved run title from the event log.
     */
    'title'?: string;
    'spec': RunSpec;
    /**
     * Absolute web UI URL for this run when server web settings are configured.
     */
    'web_url'?: string | null;
    'start'?: StartRecord | null;
    'status': RunStatus;
    'archived_at'?: string | null;
    'status_updated_at': string;
    'last_event_at': string;
    'pending_control'?: RunControlAction | null;
    /**
     * Sequence-tagged checkpoint history entries.
     */
    'checkpoints': Array<CheckpointRecord>;
    'conclusion'?: Conclusion | null;
    'sandbox'?: RunSandbox | null;
    'pull_request'?: { [key: string]: any; } | null;
    'superseded_by'?: string | null;
    'pending_interviews': { [key: string]: PendingInterviewRecord; };
    /**
     * Map from StageId (`node_id@visit`) to stage projection data.
     */
    'stages': { [key: string]: StageProjection; };
}



