/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunControlAction } from './run-control-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RunError } from './run-error';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatus } from './run-status';

export interface RunLifecycle {
    'status': RunStatus;
    'pending_control': RunControlAction | null;
    'queue_position': number | null;
    'error': RunError | null;
    'archived': boolean;
    'archived_at': string | null;
}



