/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GitContext } from './git-context';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestArgs } from './manifest-args';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestConfig } from './manifest-config';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestGoal } from './manifest-goal';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestTarget } from './manifest-target';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestWorkflow } from './manifest-workflow';

/**
 * Self-contained workflow run manifest.
 */
export interface RunManifest {
    /**
     * Manifest schema version.
     */
    'version': number;
    /**
     * Optional pre-generated run ID to use instead of allocating a new ULID.
     */
    'run_id'?: string | null;
    /**
     * Optional orchestration parent run ID. Fork and rewind lineage use separate fields and should not set this value.
     */
    'parent_id'?: string | null;
    /**
     * Optional explicit run title. The server trims leading/trailing whitespace, rejects blank values, rejects control characters and newline characters, and requires at most 100 characters.
     */
    'title'?: string | null;
    /**
     * CLI working directory at invocation time.
     */
    'cwd': string;
    'git'?: GitContext;
    'goal'?: ManifestGoal;
    'args'?: ManifestArgs;
    'target': ManifestTarget;
    'configs'?: Array<ManifestConfig>;
    'workflows': { [key: string]: ManifestWorkflow; };
}

