/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RunSandboxRuntime {
    'id': string;
    'working_directory': string;
    'repo_cloned': boolean | null;
    'clone_origin_url': string | null;
    'clone_branch': string | null;
    'workspace_root'?: string | null;
    'repos_root'?: string | null;
    'primary_repo_path'?: string | null;
    'primary_repo_link'?: string | null;
}

