/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DaytonaSettings } from './daytona-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { DockerSettings } from './docker-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxProvider } from './sandbox-provider';

export interface RunSandboxSettings {
    'provider': SandboxProvider;
    'preserve': boolean;
    'stop_on_terminal': boolean;
    'devcontainer': boolean;
    'env': { [key: string]: string; };
    'docker': DockerSettings | null;
    'daytona': DaytonaSettings | null;
}



