/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationRef } from './automation-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { DiffSummary } from './diff-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { Principal } from './principal';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequest } from './pull-request';
// May contain unused imports in some cases
// @ts-ignore
import type { RepositoryRef } from './repository-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { RunBillingSummary } from './run-billing-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { RunLifecycle } from './run-lifecycle';
// May contain unused imports in some cases
// @ts-ignore
import type { RunLinks } from './run-links';
// May contain unused imports in some cases
// @ts-ignore
import type { RunModel } from './run-model';
// May contain unused imports in some cases
// @ts-ignore
import type { RunOrigin } from './run-origin';
// May contain unused imports in some cases
// @ts-ignore
import type { RunQuestion } from './run-question';
// May contain unused imports in some cases
// @ts-ignore
import type { RunSandbox } from './run-sandbox';
// May contain unused imports in some cases
// @ts-ignore
import type { RunTimestamps } from './run-timestamps';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowRef } from './workflow-ref';

/**
 * Canonical public run shape.
 */
export interface Run {
    'id': string;
    'title': string;
    'goal': string;
    'workflow': WorkflowRef;
    'automation': AutomationRef | null;
    'repository': RepositoryRef | null;
    'created_by': Principal | null;
    'origin': RunOrigin;
    'labels': { [key: string]: string; };
    'lifecycle': RunLifecycle;
    'sandbox': RunSandbox | null;
    'models': Array<RunModel>;
    'source_directory': string | null;
    'timestamps': RunTimestamps;
    'billing': RunBillingSummary | null;
    'diff': DiffSummary | null;
    'pull_request': PullRequest | null;
    'current_question': RunQuestion | null;
    'superseded_by': string | null;
    'links': RunLinks;
}

