/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxNetworkPolicyMode } from './sandbox-network-policy-mode';

/**
 * Public-network policy for one direction.
 */
export interface SandboxNetworkPolicy {
    'mode': SandboxNetworkPolicyMode;
    /**
     * CIDR entries when `mode` is `cidr_allow_list`; empty for other modes.
     */
    'cidrs': Array<string>;
}



