/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A listening TCP service discovered inside a run sandbox.
 */
export interface SandboxService {
    /**
     * Listening TCP port.
     */
    'port': number;
    /**
     * Local bind addresses reported by `ss`.
     */
    'addresses': Array<string>;
    /**
     * Visible process summaries reported by `ss`.
     */
    'processes': Array<string>;
    /**
     * Whether the provider supports an external preview URL for this port.
     */
    'preview_supported': boolean;
}

