/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Sandbox execution provider.
 */

export const SandboxProvider = {
    LOCAL: 'local',
    DOCKER: 'docker',
    DAYTONA: 'daytona'
} as const;

export type SandboxProvider = typeof SandboxProvider[keyof typeof SandboxProvider];



