/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Resource configuration for a sandbox. Fields are nullable when the provider does not surface a value or no limit is configured.
 */
export interface SandboxResources {
    /**
     * Configured CPU cores. Null when unavailable.
     */
    'cpu_cores'?: number;
    /**
     * Memory limit in bytes. Null when unavailable or unlimited.
     */
    'memory_bytes'?: number;
    /**
     * Disk size in bytes. Null when unavailable.
     */
    'disk_bytes'?: number;
}

