/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lifecycle timestamps for a sandbox. Fields are nullable when the provider does not surface a value.
 */
export interface SandboxTimestamps {
    /**
     * When the sandbox was created.
     */
    'created_at'?: string;
    /**
     * Most recent activity timestamp reported by the provider.
     */
    'last_activity_at'?: string;
}

