/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Provider-neutral public-network policy for one direction.
 */

export const SandboxNetworkPolicyMode = {
    UNKNOWN: 'unknown',
    OPEN: 'open',
    BLOCKED: 'blocked',
    CIDR_ALLOW_LIST: 'cidr_allow_list',
    ESSENTIALS_ONLY: 'essentials_only'
} as const;

export type SandboxNetworkPolicyMode = typeof SandboxNetworkPolicyMode[keyof typeof SandboxNetworkPolicyMode];



