/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxService } from './sandbox-service';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxServiceListMeta } from './sandbox-service-list-meta';

/**
 * Non-paginated list of listening TCP services in a run sandbox.
 */
export interface SandboxServiceListResponse {
    'data': Array<SandboxService>;
    'meta': SandboxServiceListMeta;
}

