/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Normalized sandbox lifecycle state used by the control plane and UI. The original provider-specific state string is preserved in `native_state`.
 */

export const SandboxState = {
    UNKNOWN: 'unknown',
    PROVISIONING: 'provisioning',
    STARTING: 'starting',
    RUNNING: 'running',
    STOPPING: 'stopping',
    STOPPED: 'stopped',
    PAUSED: 'paused',
    DELETING: 'deleting',
    DELETED: 'deleted',
    ARCHIVED: 'archived',
    RESTORING: 'restoring',
    RESIZING: 'resizing',
    ERROR: 'error'
} as const;

export type SandboxState = typeof SandboxState[keyof typeof SandboxState];



