/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Schema of a stored secret.
 */

export const SecretType = {
    TOKEN: 'token',
    OAUTH: 'oauth',
    FILE: 'file'
} as const;

export type SecretType = typeof SecretType[keyof typeof SecretType];



