/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SessionStatus } from './session-status';

/**
 * List projection of a durable session.
 */
export interface SessionSummary {
    /**
     * Durable session identifier.
     */
    'id': string;
    'title'?: string | null;
    'status': SessionStatus;
    'working_dir'?: string | null;
    'provider'?: string | null;
    'model'?: string | null;
    'created_at': string;
    'updated_at': string;
}
