/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Persisted full-fidelity session transcript message.
 */
export interface SessionMessage {
    'kind': SessionMessageKindEnum;
    'content'?: string;
    'timestamp': string;
    'tool_calls'?: Array<any>;
    'provider_parts'?: Array<any>;
    'usage'?: any;
    'response_id'?: string;
    'results'?: Array<any>;
}

export const SessionMessageKindEnum = {
    USER: 'user',
    ASSISTANT: 'assistant',
    TOOL_RESULTS: 'tool_results',
    SYSTEM: 'system',
    STEERING: 'steering'
} as const;

export type SessionMessageKindEnum = typeof SessionMessageKindEnum[keyof typeof SessionMessageKindEnum];
