/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Append-only durable session event envelope.
 */
export interface SessionEventEnvelope {
    'seq': number;
    /**
     * Durable session identifier.
     */
    'session_id': string;
    /**
     * Durable session turn identifier.
     */
    'turn_id'?: string | null;
    'event': string;
    'properties': any;
    'ts': string;
}
