/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for creating sandbox access for a sandbox-backed run.
 */
export interface SshAccessRequest {
    /**
     * Time-to-live for time-limited access commands in minutes. Ignored by providers whose commands are not time-limited.
     */
    'ttl_minutes': number;
}

