/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BilledTokenCounts } from './billed-token-counts';
// May contain unused imports in some cases
// @ts-ignore
import type { BillingModelRef } from './billing-model-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { CommandTermination } from './command-termination';
// May contain unused imports in some cases
// @ts-ignore
import type { StageCompletion } from './stage-completion';
// May contain unused imports in some cases
// @ts-ignore
import type { StageState } from './stage-state';

/**
 * Observable projection data for one workflow stage execution.
 */
export interface StageProjection {
    'first_event_seq': number;
    'prompt'?: string | null;
    'response'?: string | null;
    'completion'?: StageCompletion | null;
    /**
     * Provider and model metadata recorded for the stage attempt.
     */
    'provider_used'?: object | null;
    'diff'?: string | null;
    /**
     * Command and environment recorded when the stage script ran.
     */
    'script_invocation'?: object | null;
    /**
     * Wall-clock and step timing metadata for the stage script.
     */
    'script_timing'?: object | null;
    /**
     * Per-branch result objects produced by a parallel stage.
     */
    'parallel_results'?: Array<object> | null;
    'output'?: string | null;
    'output_bytes'?: number | null;
    'live_streaming'?: boolean | null;
    'termination'?: CommandTermination | null;
    /**
     * Wall-clock time the latest attempt of this stage started, if known.
     */
    'started_at'?: string | null;
    /**
     * Wall-clock duration of the stage\'s latest terminal attempt, if known.
     */
    'duration_ms'?: number | null;
    'usage': BilledTokenCounts;
    'model'?: BillingModelRef | null;
    /**
     * Lifecycle state of the stage projection.
     */
    'state': StageState;
}



