/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IntegrationConnectionStatus } from './integration-connection-status';
// May contain unused imports in some cases
// @ts-ignore
import type { IntegrationProvider } from './integration-provider';
// May contain unused imports in some cases
// @ts-ignore
import type { IntegrationStatus } from './integration-status';

/**
 * Runtime status for one server integration.
 */
export interface SystemIntegrationStatus {
    'provider': IntegrationProvider;
    /**
     * Whether configuration allows this integration to run.
     */
    'enabled': boolean;
    /**
     * Whether the integration has required non-secret settings and vault credentials.
     */
    'configured': boolean;
    'status': IntegrationStatus;
    /**
     * Missing setting or vault key names required before the integration can run.
     */
    'missing_credentials': Array<string>;
    'connection': IntegrationConnectionStatus | null;
    /**
     * Non-secret display hints for the integration.
     */
    'metadata': { [key: string]: string; };
}
