/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TurnStatus } from './turn-status';

/**
 * One externally submitted input plus terminal output metadata. Full resumable context is stored on SessionRecord.runtime_context.
 */
export interface TurnRecord {
    /**
     * Durable session turn identifier.
     */
    'id': string;
    /**
     * Durable session identifier.
     */
    'session_id': string;
    'input': string;
    'status': TurnStatus;
    'output'?: string | null;
    'error'?: string | null;
    'created_at': string;
    'updated_at': string;
    'completed_at'?: string | null;
}
