/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response containing a signed noVNC preview URL for a Daytona sandbox.
 */
export interface VncPreviewResponse {
    /**
     * Signed noVNC preview URL.
     */
    'url': string;
    /**
     * Sandbox provider that produced the VNC preview.
     */
    'provider': string;
    /**
     * noVNC port exposed by the sandbox.
     */
    'port': number;
    /**
     * Signed URL time-to-live in seconds.
     */
    'expires_in_secs': number;
}

